server:
  port: 8080
spring:
  application:
    name: hotel-service

  # DB
  datasource:
    url: jdbc:h2:mem:bookingdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true

  # Zipkin
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

# App description
info:
  app:
    name: Hotel microservice
    description: Application to reserve an rooms
    version: 1.0.0


# Resilience4j
# Circuit Breaker Pattern
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      searchByHotelIdSupportCB:
        minimumNumberOfCalls: 7
        failureRateThreshold: 50
        waitDurationInOpenState: 20000
        permittedNumberOfCallsInHalfOpenState: 3

# Retry Pattern
  retry:
    instance:
      searchByHotelIdSupportRetry:
        maxAttempts: 3
        waitDuration: 1500

# Logging
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  
# General information
hotel-service:
  msg: "Welcome to the Reservations Hotels applications"
  build-version: 1

# Mail information
  mailDetails:
    hostName: "default-gibbfarc17@gmail.com"
    port: 5420
    from: "default-gibbfarc17@gmail.com"
    subject: "Your Reservations is ready"
